kevin_bacon = Node.new("Kevin Bacon")
ryan_reynolds = Node.new("Ryan Reynolds")
jeff_bridges = Node.new("Jeff Bridges")
michael_fassbender = Node.new("Michael Fassbender")
jennifer_lawrence = Node.new("Jennifer Lawrence")
brad_pitt = Node.new("Brad Pitt")
james_mcavoy = Node.new("James McAvoy")
mary_l_p = Node.new("Mary-Louise Parker")
stephanie_szostak = Node.new("Stephanie Szostak")
sean_penn = Node.new("Sean Penn")
tim_robbins = Node.new("Tim Robbins")
laurence_fishburne = Node.new("Laurence Fishburne")
marcia_gay_harden = Node.new("Marcia Gay Harden")
laura_linney = Node.new("Laura Linney")
kevin_chapman = Node.new("Kevin Chapman")
emmy_rossum = Node.new("Emmy Rossum")
elisabeth_shue = Node.new("Elisabeth Shue")
josh_brolin = Node.new("Josh Brolin")
kim_dickens = Node.new("Kim Dickens")
greg_grunberg = Node.new("Greg Grunberg")
joey_slotnick = Node.new("Joey Slotnick")
morena_baccarin = Node.new("Morena Baccarin")
julian_dennison = Node.new("Julian Dennison")
zazie_beetz = Node.new("Zazie Beetz")
tj_miller = Node.new("T.J. Miller")
leslie_uggams = Node.new("Leslie Uggams")
karan_soni = Node.new("Karan Soni")
denzel_washington = Node.new("Denzel Washington")
vera_farmiga = Node.new("Vera Farmiga")
brendan_gleeson = Node.new("Brendan Gleeson")
sam_shepard = Node.new("Sam Shepard")
liam_cunningham = Node.new("Liam Cunningham")
joel_kinnaman = Node.new("Joel Kinnaman")
liev_schreiber = Node.new("Liev Schreiber")
danny_huston = Node.new("Danny Huston")
lynn_collins = Node.new("Lynn Collins")
dominic_monaghan = Node.new("Dominic Monaghan")
taylor_kitsch = Node.new("Taylor Kitsch")
taron_egerton = Node.new("Taron Egerton")
edward_holcroft = Node.new("Edward Holcroft")
julianne_moore = Node.new( "Julianne Moore")
colin_firth = Node.new("Colin Firth")
michael_gambon = Node.new("Michael Gambon")
hailee_steinfeld = Node.new("Hailee Steinfeld")
matt_damon = Node.new("Matt Damon")
barry_pepper = Node.new("Barry Pepper")
domhnall_gleeson = Node.new("Domhnall Gleeson")
robert_d_jr = Node.new("Robert Downey Jr.")
terrence_howard = Node.new("Terrence Howard")
gwyneth_paltrow = Node.new("Gwyneth Paltrow")
clark_gregg = Node.new("Clark Gregg")
paul_bettany = Node.new("Paul Bettany")
jon_favreau = Node.new("Jon Favreau")
john_goodman = Node.new("John Goodman")
steve_buscemi = Node.new("Steve Buscemi")
david_huddleston = Node.new("David Huddleston")
philip_seymour_hoffman = Node.new("Philip Seymour Hoffman")
tara_reid = Node.new("Tara Reid")
john_turturro = Node.new("John Turturro")
miles_teller = Node.new("Miles Teller")
jennifer_connelly = Node.new("Jennifer Connelly")
nicholas_hoult = Node.new("Nicholas Hoult")
oscar_isaac = Node.new("Oscar Isaac")
rose_byrne = Node.new("Rose Byrne")
evan_peters = Node.new("Evan Peters")
sophie_turner = Node.new("Sophie Turner")
josh_helman = Node.new("Josh Helman")
noomie_rapace = Node.new("Noomi Rapace")
charlize_theron = Node.new("Charlize Theron")
idris_elba = Node.new( "Idris Elba")
guy_pearce = Node.new("Guy Pearce")
benedict_wong = Node.new("Benedict Wong")
christoph_waltz = Node.new("Christoph Waltz")
eli_roth = Node.new("Eli Roth")
diane_kruger = Node.new("Diane Kruger")
daniel_bruhl = Node.new("Daniel Bruhl")
til_schweiger = Node.new("Til Schweiger")
bj_novak = Node.new("B.J. Novak")
gerard_butler = Node.new("Gerard Butler")
lena_headey = Node.new("Lena Headey")
dominic_west = Node.new("Dominic West")
david_wenham = Node.new("David Wenham")
rodrigo_santoro = Node.new("Rodrigo Santoro")
vincent_regan = Node.new("Vincent Regan")
joel_edgerton = Node.new("Joel Edgerton")
matthias_schoenaerts = Node.new("Matthias Schoenaerts")
charlotte_rampling = Node.new("Charlotte Rampling")
joely_richardson = Node.new("Joely Richardson")
bill_camp = Node.new("Bill Camp")
jeremy_irons = Node.new("Jeremy Irons")
christian_bale = Node.new("Christian Bale")
bradley_cooper = Node.new("Bradley Cooper")
amy_adams = Node.new("Amy Adams")
jeremy_renner = Node.new("Jeremy Renner")
louis_ck = Node.new("Louis C.K.")
jack_huston = Node.new("Jack Huston")
michael_pena = Node.new("Michael Pena")
shea_wigham = Node.new("Shea Whigham")
chris_tucker = Node.new("Chris Tucker")
robert_de_niro = Node.new("Robert De Niro")
jackie_weaver = Node.new("Jackie Weaver")
paul_herman = Node.new("Paul Herman")
john_bernthal = Node.new("John Bernthal")
shia_labeouf = Node.new("Shia LaBeouf")
logan_lerman = Node.new("Logan Lerman")
jim_parrack = Node.new("Jim Parrack")
brad_w_henke = Node.new("Brad William Henke")
kevin_vance = Node.new("Kevin Vance")
ryan_gosling = Node.new("Ryan Gosling")
charlie_talbert = Node.new("Charlie Talbert")
hunter_burke = Node.new("Hunter Burke")
steve_carell = Node.new("Steve Carell")
marisa_tomei = Node.new("Marisa Tomei")
jonah_hill = Node.new("Jonah Hill")
robin_wright = Node.new("Robin Wright")
chris_pratt = Node.new("Chris Pratt")
stephen_bishop = Node.new("Stephen Bishop")
scoot_mcnairy = Node.new("Scoot McNairy")
ben_mendelsohn = Node.new("Ben Mendelsohn")
james_gandolfini = Node.new("James Gandolfini")
richard_jenkins = Node.new("Richard Jenkins")
vincent_curatola = Node.new("Vincent Curatola")
ray_liotta = Node.new("Ray Liotta")
christopher_berry = Node.new("Christopher Berry")
trevor_long = Node.new("Trevor Long")
george_clooney = Node.new("George Clooney")
michael_mantell = Node.new("Michael Mantell")
elliot_gould = Node.new("Elliot Gould")
al_pacino = Node.new("Al Pacino")
don_cheadle = Node.new("Don Cheadle")
bernie_mac = Node.new("Bernie Mac")
carl_reiner = Node.new("Carl Reiner")
julian_glover = Node.new("Julian Glover")
brian_cox = Node.new("Brian Cox")
eric_bana = Node.new("Eric Bana")
orlando_bloom = Node.new("Orlando Bloom")




kevin_bacon.film_actor_hash["X-Men: First Class"] = [james_mcavoy, michael_fassbender, jennifer_lawrence]
kevin_bacon.film_actor_hash["R.I.P.D"] = [ryan_reynolds, jeff_bridges, mary_l_p, stephanie_szostak]
kevin_bacon.film_actor_hash["Mystic River"] = [sean_penn, tim_robbins, laurence_fishburne, marcia_gay_harden, laura_linney, kevin_chapman, emmy_rossum]
kevin_bacon.film_actor_hash["Hollow Man"] = [elisabeth_shue, josh_brolin, kim_dickens, greg_grunberg, joey_slotnick]


ryan_reynolds.film_actor_hash["R.I.P.D"] = [kevin_bacon, jeff_bridges, mary_l_p, stephanie_szostak]
ryan_reynolds.film_actor_hash["Deadpool 2"] = [josh_brolin, morena_baccarin, julian_dennison, zazie_beetz, tj_miller, leslie_uggams, karan_soni]
ryan_reynolds.film_actor_hash["Safe House"] = [denzel_washington, vera_farmiga, brendan_gleeson, sam_shepard, liam_cunningham, joel_kinnaman]
ryan_reynolds.film_actor_hash["X-men Origins: Wolverine"] = [liev_schreiber, danny_huston, lynn_collins, dominic_monaghan, taylor_kitsch]

jeff_bridges.film_actor_hash["Kingsman: The Golden Circle"] = [taron_egerton, edward_holcroft, julianne_moore, colin_firth, michael_gambon]
jeff_bridges.film_actor_hash["True Grit"] = [josh_brolin, hailee_steinfeld, matt_damon, barry_pepper, domhnall_gleeson]
jeff_bridges.film_actor_hash["Iron Man"] = [robert_d_jr, terrence_howard, gwyneth_paltrow, clark_gregg, paul_bettany, jon_favreau]
jeff_bridges.film_actor_hash["The Big Lebowski"] = [john_goodman, julianne_moore, steve_buscemi, david_huddleston, philip_seymour_hoffman, tara_reid, john_turturro]
jeff_bridges.film_actor_hash["Only The Brave"] = [miles_teller, josh_brolin, jennifer_connelly, taylor_kitsch]

michael_fassbender.film_actor_hash["X-men: Apocalypse"] = [james_mcavoy, jennifer_lawrence, nicholas_hoult, oscar_isaac, rose_byrne, evan_peters, sophie_turner, josh_helman]
michael_fassbender.film_actor_hash["Prometheus"] = [noomie_rapace, charlize_theron, idris_elba, guy_pearce, benedict_wong]
michael_fassbender.film_actor_hash["Inglourious Basterds"] = [brad_pitt, christoph_waltz, eli_roth, diane_kruger, daniel_bruhl, til_schweiger, bj_novak]
michael_fassbender.film_actor_hash["300"] = [gerard_butler, lena_headey, dominic_west, david_wenham, rodrigo_santoro, vincent_regan]

jennifer_lawrence.film_actor_hash["Red Sparrow"] = [joel_edgerton, matthias_schoenaerts, charlotte_rampling, mary_l_p, joely_richardson, bill_camp, jeremy_irons]
jennifer_lawrence.film_actor_hash["American Hustle"] = [christian_bale, bradley_cooper, amy_adams, jeremy_renner, louis_ck, jack_huston, michael_pena, shea_wigham]
jennifer_lawrence.film_actor_hash["Silver Linings Playbook"] = [bradley_cooper, chris_tucker, robert_de_niro, jackie_weaver, shea_wigham, paul_herman]

brad_pitt.film_actor_hash["Fury"] = [shia_labeouf, logan_lerman, michael_pena, john_bernthal, jim_parrack, brad_w_henke, kevin_vance]
brad_pitt.film_actor_hash["The Big Short"] = [ryan_gosling, christian_bale, charlie_talbert, hunter_burke, steve_carell, marisa_tomei]
brad_pitt.film_actor_hash["Moneyball"] = [jonah_hill, philip_seymour_hoffman, robin_wright, chris_pratt, stephen_bishop]
brad_pitt.film_actor_hash["Killing Them Softly"] = [scoot_mcnairy, ben_mendelsohn, james_gandolfini, richard_jenkins, vincent_curatola, ray_liotta, sam_shepard, christopher_berry, trevor_long]
brad_pitt.film_actor_hash["Inglourious Basterds"] = [michael_fassbender, christoph_waltz, eli_roth, diane_kruger, daniel_bruhl, til_schweiger, bj_novak]
brad_pitt.film_actor_hash["Ocean's Thirteen"] = [george_clooney, matt_damon, michael_mantell, elliot_gould, al_pacino, don_cheadle, bernie_mac, carl_reiner]
brad_pitt.film_actor_hash["Troy"] = [julian_glover, brian_cox, brendan_gleeson, diane_kruger, eric_bana, orlando_bloom]
